-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgplck98mskOZ8ILpA
qWWG5RiHr972seoNpw8gW35abwygCgYIKoZIzj0DAQehRANCAATDYNcMkKqPAU6C
xrrtVXBkECv/3ohn6dAsCiG8EsemeHnThQnBu17foGb+oiez/dVWVsFxRICYjPbg
q7HXhqTk
-----END PRIVATE KEY-----